DROP TABLE IF EXISTS videos CASCADE;
DROP TABLE IF EXISTS exams CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS admin_access_keys CASCADE;
DROP TABLE IF EXISTS admin_license_keys CASCADE;
DROP TABLE IF EXISTS admins CASCADE;

CREATE TABLE admins (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20),
    password_hash VARCHAR(255) NOT NULL,
    avatar_url VARCHAR(255) DEFAULT 'default',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin_license_keys (
    id SERIAL PRIMARY KEY,
    key_code VARCHAR(50) UNIQUE NOT NULL,
    is_used BOOLEAN DEFAULT FALSE
);

CREATE TABLE admin_access_keys (
    id SERIAL PRIMARY KEY,
    admin_id INTEGER UNIQUE REFERENCES admins(id) ON DELETE CASCADE,
    key_code VARCHAR(50) UNIQUE NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE exams (
    id SERIAL PRIMARY KEY,
    admin_id INTEGER REFERENCES admins(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    contest_link TEXT NOT NULL,
    access_code VARCHAR(50) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE students (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    admin_id INTEGER REFERENCES admins(id) ON DELETE CASCADE,
    ip_address VARCHAR(50),
    machine_id VARCHAR(255),
    status VARCHAR(100) DEFAULT 'ONLINE',
    last_ping TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO admin_license_keys (key_code) VALUES 
('CTNS-2026-VIP-KEY-001'), ('CTNS-2026-VIP-KEY-002'), 
('CTNS-2026-VIP-KEY-003'), ('CTNS-2026-VIP-KEY-004'), ('CTNS-2026-VIP-KEY-005');